version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"
    assignees:
      - casjay
    reviewers:
      - casjay

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - casjay
    reviewers:
      - casjay

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - casjay
    reviewers:
      - casjay
