-- Default Settings
INSERT OR IGNORE INTO settings (key, value) VALUES
('site_name', 'Cassocial'),
('site_url', 'https://casjay.link'),
('initialized', 'false'),
('setup_completed', 'false'),
('maintenance_mode', 'false'),
('maintenance_message', 'We are upgrading our systems. Be back soon!'),
('maintenance_bypass_ips', '["127.0.0.1", "::1"]'),
('registration_enabled', 'true'),
('registration_requires_approval', 'false'),
('email_verification_required', 'true'),
('max_links_per_profile', '100'),
('max_profiles_per_user', '5'),
('upload_max_size_mb', '5'),
('allowed_image_types', '["jpg", "jpeg", "png", "gif", "webp"]'),
('cache_ttl_seconds', '3600'),
('rate_limit_requests', '100'),
('rate_limit_window_seconds', '60'),
('backup_enabled', 'true'),
('backup_retention_days', '30'),
('backup_time', '03:00'),
('analytics_retention_days', '90'),
('analytics_anonymous_mode', 'false'),
('analytics_sampling_rate', '100'),
('session_timeout_minutes', '1440'),
('password_min_length', '8'),
('password_require_uppercase', 'true'),
('password_require_number', 'true'),
('password_require_special', 'false'),
('two_factor_enabled', 'false'),
('qr_code_size', '256'),
('default_theme_id', '00000000-0000-0000-0000-000000000001'),
('enable_custom_css', 'true'),
('enable_custom_domains', 'true'),
('ssl_auto_renew', 'true'),
('ssl_renew_days_before', '30'),
('smtp_provider', 'CUSTOM'),
('smtp_host', ''),
('smtp_port', '587'),
('smtp_security', 'STARTTLS'),
('smtp_user', ''),
('smtp_password', ''),
('smtp_from_name', 'Cassocial'),
('smtp_from_address', ''),
('admin_email', ''),
('smtp_enabled', 'false'),
('smtp_retry_count', '3'),
('smtp_retry_delay', '60'),
('notify_emergency', 'true'),
('notify_certificate', 'true'),
('notify_bug_report', 'true'),
('notify_user_registration', 'true'),
('notify_domain_verification', 'true'),
('notify_backup_status', 'true'),
('notify_high_traffic', 'true'),
('notification_batch_delay', '300'),
('default_footer', '[{"type": "text", "content": "© 2025 {username}"}, {"type": "links", "content": [{"text": "Privacy", "url": "/privacy"}, {"text": "Terms", "url": "/terms"}]}]'),
('gradient_presets', '[{"name": "Sunset", "value": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"}, {"name": "Ocean", "value": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"}, {"name": "Forest", "value": "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)"}, {"name": "Fire", "value": "linear-gradient(135deg, #fc466b 0%, #3f5efb 100%)"}]');

-- Default Themes
INSERT OR IGNORE INTO themes (id, name, background_color, text_color, link_background, link_hover, link_text, border_radius, font_family, is_premium) VALUES
('00000000-0000-0000-0000-000000000001', 'Dark (Dracula)', '#282a36', '#f8f8f2', '#44475a', '#6272a4', '#f8f8f2', '12px', 'Inter, system-ui, sans-serif', 0),
('00000000-0000-0000-0000-000000000002', 'Light', '#ffffff', '#212529', '#ffffff', '#f8f9fa', '#212529', '12px', 'Inter, system-ui, sans-serif', 0);
